%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\laura\Documents\SPIN\EEG_data\labels.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/25 16:44:58

%% Initialize variables.
filename = get_path_ui(pwd, '*.csv', 'Labels CSV', 'It is the CSV file of all the labels for different scenes, a copy is kept on the Google Drive.', true);
delimiter = ',';

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: text (%s)
%   column3: categorical (%C)
%	column4: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%s%C%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
labels = table(dataArray{1:end-1}, 'VariableNames', {'scene','tag','stream','type'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;